name: Copy Deployment Engine Image
description: Copy a deployment engine image from Azure Container Registry to GitHub Container Registry.
inputs:
  tag:
    description: Tag to apply to the destination image and pull from the source image.
    required: true
  acr-source-name:
    description: Name of the Azure Container Registry that hosts the deployment engine image.
    required: true
  acr-source-repository:
    description: Repository name for the image inside the ACR.
    required: true
  ghcr-destination-repository:
    description: Repository path in the destination registry.
    required: true

# Expected environment variables:
#   ACR_AZURE_CLIENT_ID
#   ACR_AZURE_TENANT_ID
#   ACR_AZURE_SUBSCRIPTION_ID
#   GHCR_TOKEN

runs:
  using: composite
  steps:
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ env.ACR_AZURE_CLIENT_ID }}
        tenant-id: ${{ env.ACR_AZURE_TENANT_ID }}
        subscription-id: ${{ env.ACR_AZURE_SUBSCRIPTION_ID }}

    - name: Log in to ACR
      shell: bash
      run: |
        az acr login --name "${{ inputs.acr-name }}"

    - name: Log in to GHCR
      shell: bash
      env:
        GHCR_TOKEN: ${{ env.GHCR_TOKEN }}
      run: |
        echo "${GHCR_TOKEN}" | docker login ghcr.io \
          --username x-access-token \
          --password-stdin

    - name: Copy Deployment Engine image from ACR to GHCR
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
        ACR_NAME: ${{ inputs.acr-source-name }}
        SRC_REPO: ${{ inputs.acr-source-repository }}
        DEST_REPO: ${{ inputs.ghcr-destination-repository }}
      run: |
        docker buildx imagetools create \
          --tag "ghcr.io/${DEST_REPO}:${TAG}" \
          "${ACR_NAME}.azurecr.io/${SRC_REPO}:${TAG}"
