name: Copy Deployment Engine Image
description: Copy a deployment engine image from Azure Container Registry to GitHub Container Registry.
inputs:
  tag:
    description: Tag to apply to the destination image and pull from the source image.
    required: true
  src_image:
    description: Name of the source image in Azure Container Registry (e.g. myregistry.azurecr.io/deployment-engine).
    required: true
  dest_image:
    description: Name of the GitHub Container Registry repository to push the deployment engine image to (e.g. ghcr.io/myorg/deployment-engine).
    required: true

# Expected environment variables:
#   ACR_AZURE_CLIENT_ID
#   ACR_AZURE_TENANT_ID
#   ACR_AZURE_SUBSCRIPTION_ID
#   GHCR_TOKEN

runs:
  using: composite
  steps:
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ env.ACR_AZURE_CLIENT_ID }}
        tenant-id: ${{ env.ACR_AZURE_TENANT_ID }}
        subscription-id: ${{ env.ACR_AZURE_SUBSCRIPTION_ID }}

    - name: Log in to ACR
      shell: bash
      env:
        SRC_IMAGE: ${{ inputs.src_image }}
      run: |
        # Example: SRC_IMAGE=myregistry.azurecr.io/deployment-engine -> REGISTRY_NAME=myregistry
        REGISTRY="${SRC_IMAGE%%/*}"
        REGISTRY_NAME="${REGISTRY%%.azurecr.io}"
        az acr login --name "${REGISTRY_NAME}"

    - name: Log in to GHCR
      shell: bash
      env:
        GHCR_TOKEN: ${{ env.GHCR_TOKEN }}
      run: |
        echo "${GHCR_TOKEN}" | docker login ghcr.io \
          --username x-access-token \
          --password-stdin

    - name: Copy Deployment Engine image from ACR to GHCR
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
        SRC_IMAGE: ${{ inputs.src_image }}
        DEST_IMAGE: ${{ inputs.dest_image }}
      run: |
        docker buildx imagetools create \
          --tag "${DEST_IMAGE}:${TAG}" \
          "${SRC_IMAGE}:${TAG}"
